# Generated by Django 5.2.7 on 2025-11-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dance_style', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DanceSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
