# Generated by Django 5.2.7 on 2025-11-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_app', '0002_dancer_danceschool_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceschool',
            name='address',
            field=models.CharField(default='Centar Podgorice', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danceschool',
            name='classes_per_week',
            field=models.PositiveIntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danceschool',
            name='dances_taught',
            field=models.TextField(default='ALL', help_text='List of dances taught, separated by commas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danceschool',
            name='phone_number',
            field=models.CharField(default='38269123456', max_length=20),
            preserve_default=False,
        ),
    ]
