# Generated by Django 5.2.7 on 2025-11-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_app', '0003_danceschool_address_danceschool_classes_per_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('dancer', 'Dancer'), ('school', 'Dance School')], max_length=10)),
            ],
        ),
    ]
