# Generated by Django 5.2.7 on 2025-11-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_app', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dancer',
            old_name='name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='dancer',
            name='email',
        ),
        migrations.AddField(
            model_name='dancer',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dancer',
            name='first_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dancer',
            name='last_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dancer',
            name='phone',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
